# Author: Oleksandr Korniienko
# Assessment 1 Computer Systems SETU 2025

# This little programm takes a file with space-separated fields: id, name, ocupation, departament wages as the first parameter. 
# If file doesn't exist it will be created automatically. If the first parameter not entered it will look for the employees.txt or create it
# The user can add, delete and see the list in the table format 
# if any field has the space it's replaced with the underscore "_"


# Here was my attempt to make it in one line:
# [[ -f $1 ]] && file=$1 || 
# (( [[ ! ("$1" = "employee.txt") && ! (-f $1) ]] && echo "creating " $1; touch $1;) || 
# (echo "No parameters entered. Checking if the employee.txt exist"; [[ -f employee.txt ]] && echo "The employee.txt exist. Opening..."; file=employee.txt || echo "The file doesn't exist. Creating a new employee.txt"; touch employee.txt; file=employee.txt))

clear
file=$1
#./edit.sh $file edit_id 8
./edit.sh $file edit_wages 6

./menu.sh $1

clear
echo "==============================================================================="
echo "||                                  Welcome                                  ||"
echo "==============================================================================="
echo "||                                                                           ||"
echo "||                                                                           ||"
echo "||                                                                           ||"
echo "||                                                                           ||"
echo "||                                                                           ||"
echo "||                                                                           ||"
echo "||                                                                           ||"
echo "||                                                                           ||"
echo "||                                                                           ||"
echo "==============================================================================="
sleep 0.05
clear
echo "==============================================================================="
echo "||                                  Welcome                                  ||"
echo "==============================================================================="
echo "||                                                                           ||"
echo "||                                                                           ||"
echo "||                                                                           ||"
echo "||                                                                           ||"
echo "||                                                                           ||"
echo "||                                                                           ||"
echo "||                                                                           ||"
echo "||                                                                           ||"
echo "||                      Employee data storage program                        ||"
echo "==============================================================================="
sleep 0.05
clear
echo "==============================================================================="
echo "||                                  Welcome                                  ||"
echo "==============================================================================="
echo "||                                                                           ||"
echo "||                                                                           ||"
echo "||                                                                           ||"
echo "||                                                                           ||"
echo "||                                                                           ||"
echo "||                                                                           ||"
echo "||                                                                           ||"
echo "||                      Employee data storage program                        ||"
echo "||                                                                           ||"
echo "==============================================================================="
sleep 0.05
clear
echo "==============================================================================="
echo "||                                  Welcome                                  ||"
echo "==============================================================================="
echo "||                                                                           ||"
echo "||                                                                           ||"
echo "||                                                                           ||"
echo "||                                                                           ||"
echo "||                                                                           ||"
echo "||                                                                           ||"
echo "||                      Employee data storage program                        ||"
echo "||                                                                           ||"
echo "||                                                                           ||"
echo "==============================================================================="
sleep 0.05
clear
echo "==============================================================================="
echo "||                                  Welcome                                  ||"
echo "==============================================================================="
echo "||                                                                           ||"
echo "||                                                                           ||"
echo "||                                                                           ||"
echo "||                                                                           ||"
echo "||                                                                           ||"
echo "||                      Employee data storage program                        ||"
echo "||                                                                           ||"
echo "||                                                                           ||"
echo "||                                                                           ||"
echo "==============================================================================="
sleep 0.05
clear
echo "==============================================================================="
echo "||                                  Welcome                                  ||"
echo "==============================================================================="
echo "||                                                                           ||"
echo "||                                                                           ||"
echo "||                                                                           ||"
echo "||                                                                           ||"
echo "||                                                                           ||"
echo "||                      Employee data storage program                        ||"
echo "||                                                                           ||"
echo "||                                                                           ||"
echo "||                                                                           ||"
echo "==============================================================================="
sleep 0.05
clear
echo "==============================================================================="
echo "||                                  Welcome                                  ||"
echo "==============================================================================="
echo "||                                                                           ||"
echo "||                                                                           ||"
echo "||                                                                           ||"
echo "||                                                                           ||"
echo "||                      Employee data storage program                        ||"
echo "||                                                                           ||"
echo "||                                                                           ||"
echo "||                                                                           ||"
echo "||                                                                           ||"
echo "==============================================================================="
sleep 0.05
clear
echo "==============================================================================="
echo "||                                  Welcome                                  ||"
echo "==============================================================================="
echo "||                                                                           ||"
echo "||                                                                           ||"
echo "||                                                                           ||"
echo "||                      Employee data storage program                        ||"
echo "||                                                                           ||"
echo "||                                                                           ||"
echo "||                                                                           ||"
echo "||                                                                           ||"
echo "||                                                                           ||"
echo "==============================================================================="
sleep 0.05
clear
echo "==============================================================================="
echo "||                                  Welcome                                  ||"
echo "==============================================================================="
echo "||                                                                           ||"
echo "||                                                                           ||"
echo "||                      Employee data storage program                        ||"
echo "||                                                                           ||"
echo "||                                                                           ||"
echo "||                                                                           ||"
echo "||                                                                           ||"
echo "||                                                                           ||"
echo "||                                                                           ||"
echo "==============================================================================="
sleep 0.05
clear
echo "==============================================================================="
echo "||                                  Welcome                                  ||"
echo "==============================================================================="
echo "||                                                                           ||"
echo "||                      Employee data storage program                        ||"
echo "||                                                                           ||"
echo "||                                                                           ||"
echo "||                                                                           ||"
echo "||                                                                           ||"
echo "||                                                                           ||"
echo "||                                                                           ||"
echo "||                                                                           ||"
echo "==============================================================================="
sleep 0.5
clear
echo "==============================================================================="
echo "||                                  Welcome                                  ||"
echo "==============================================================================="
echo "||                                                                           ||"
echo "||                      Employee data storage program                        ||"
echo "||                                                                           ||"
echo "||                                                                           ||"
echo "||                                                                           ||"
echo "||                                                                           ||"
echo "||                                                                           ||"
echo "||                                                                           ||"
echo "||                             Computer Systems                              ||"
echo "==============================================================================="
sleep 0.05
clear
echo "==============================================================================="
echo "||                                  Welcome                                  ||"
echo "==============================================================================="
echo "||                                                                           ||"
echo "||                      Employee data storage program                        ||"
echo "||                                                                           ||"
echo "||                                                                           ||"
echo "||                                                                           ||"
echo "||                                                                           ||"
echo "||                                                                           ||"
echo "||                             Computer Systems                              ||"
echo "||                               Assessment 2                                ||"
echo "==============================================================================="
sleep 0.05
clear
echo "==============================================================================="
echo "||                                  Welcome                                  ||"
echo "==============================================================================="
echo "||                                                                           ||"
echo "||                      Employee data storage program                        ||"
echo "||                                                                           ||"
echo "||                                                                           ||"
echo "||                                                                           ||"
echo "||                                                                           ||"
echo "||                             Computer Systems                              ||"
echo "||                               Assessment 2                                ||"
echo "||                                                                           ||"
echo "==============================================================================="
sleep 0.05
clear
echo "==============================================================================="
echo "||                                  Welcome                                  ||"
echo "==============================================================================="
echo "||                                                                           ||"
echo "||                      Employee data storage program                        ||"
echo "||                                                                           ||"
echo "||                                                                           ||"
echo "||                                                                           ||"
echo "||                             Computer Systems                              ||"
echo "||                               Assessment 2                                ||"
echo "||                                                                           ||"
echo "||                                                                           ||"
echo "==============================================================================="
sleep 0.05
clear
echo "==============================================================================="
echo "||                                  Welcome                                  ||"
echo "==============================================================================="
echo "||                                                                           ||"
echo "||                      Employee data storage program                        ||"
echo "||                                                                           ||"
echo "||                                                                           ||"
echo "||                             Computer Systems                              ||"
echo "||                               Assessment 2                                ||"
echo "||                                                                           ||"
echo "||                                                                           ||"
echo "||                                                                           ||"
echo "==============================================================================="
sleep 0.05
clear
echo "==============================================================================="
echo "||                                  Welcome                                  ||"
echo "==============================================================================="
echo "||                                                                           ||"
echo "||                      Employee data storage program                        ||"
echo "||                                                                           ||"
echo "||                             Computer Systems                              ||"
echo "||                               Assessment 2                                ||"
echo "||                                                                           ||"
echo "||                                                                           ||"
echo "||                                                                           ||"
echo "||                                                                           ||"
echo "==============================================================================="
sleep 0.5
clear
echo "==============================================================================="
echo "||                                  Welcome                                  ||"
echo "==============================================================================="
echo "||                                                                           ||"
echo "||                      Employee data storage program                        ||"
echo "||                                                                           ||"
echo "||                             Computer Systems                              ||"
echo "||                               Assessment 2                                ||"
echo "||                                                                           ||"
echo "||                                                                           ||"
echo "||                                                                           ||"
echo "||                    by Oleksandr Korniienko 20114792                       ||"
echo "==============================================================================="
sleep 0.05
clear
echo "==============================================================================="
echo "||                                  Welcome                                  ||"
echo "==============================================================================="
echo "||                                                                           ||"
echo "||                      Employee data storage program                        ||"
echo "||                                                                           ||"
echo "||                             Computer Systems                              ||"
echo "||                               Assessment 2                                ||"
echo "||                                                                           ||"
echo "||                                                                           ||"
echo "||                    by Oleksandr Korniienko 20114792                       ||"
echo "||                                                                           ||"
echo "==============================================================================="
sleep 0.05
clear
echo "==============================================================================="
echo "||                                  Welcome                                  ||"
echo "==============================================================================="
echo "||                                                                           ||"
echo "||                      Employee data storage program                        ||"
echo "||                                                                           ||"
echo "||                             Computer Systems                              ||"
echo "||                               Assessment 2                                ||"
echo "||                                                                           ||"
echo "||                    by Oleksandr Korniienko 20114792                       ||"
echo "||                                                                           ||"
echo "||                                                                           ||"
echo "==============================================================================="
sleep 0.5
clear
echo "==============================================================================="
echo "||                                  Welcome                                  ||"
echo "==============================================================================="
echo "||                                                                           ||"
echo "||                      Employee data storage program                        ||"
echo "||                                                                           ||"
echo "||                             Computer Systems                              ||"
echo "||                               Assessment 2                                ||"
echo "||                                                                           ||"
echo "||                    by Oleksandr Korniienko 20114792                       ||"
echo "||                                                                           ||"
echo "||                            SETU Waterford 2025                            ||"
echo "==============================================================================="
sleep 0.05
clear
echo "==============================================================================="
echo "||                                  Welcome                                  ||"
echo "==============================================================================="
echo "||                                                                           ||"
echo "||                      Employee data storage program                        ||"
echo "||                                                                           ||"
echo "||                             Computer Systems                              ||"
echo "||                               Assessment 2                                ||"
echo "||                                                                           ||"
echo "||                    by Oleksandr Korniienko 20114792                       ||"
echo "||                            SETU Waterford 2025                            ||"
echo "||                                                                           ||"
echo "==============================================================================="
sleep 1
clear
./menu.sh $1